# Generated by Django 4.1 on 2022-08-18 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('customer_address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('customer_city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Пользователь оборудования',
                'verbose_name_plural': 'Пользователи оборудования',
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Произоводитель')),
                ('model', models.CharField(max_length=255, verbose_name='Модель оборудования')),
            ],
            options={
                'verbose_name': 'Оборудавние в наличии',
                'verbose_name_plural': 'Оборудование в наличии',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceInField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Серийный номер')),
                ('owner_status', models.CharField(max_length=255, verbose_name='Статус принадлежности')),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_api.device', verbose_name='Id оборудования')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_api.customer', verbose_name='Id пользователя')),
            ],
            options={
                'verbose_name': 'Используемое оборудавние ',
                'verbose_name_plural': 'Используемые оборудования',
                'db_table': 'devicesInField',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_description', models.TextField(verbose_name='Описание проблемы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее изменение')),
                ('order_status', models.CharField(choices=[('open', 'открыта'), ('closed', 'закрыта'), ('in progress', 'в работе'), ('need info', 'нужна информация')], max_length=100, verbose_name='Статус заявки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_api.customer', verbose_name='Пользователь')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='project_api.deviceinfield', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'orders',
            },
        ),
    ]
